# Generated by Django 4.2.5 on 2023-10-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='images/avatar-default.jpg', upload_to='images/'),
        ),
    ]
