# Generated by Django 4.2.5 on 2023-10-04 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
