# Generated by Django 4.2.5 on 2023-10-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_product_desc_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
