# Generated by Django 4.2.5 on 2023-10-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
