# Generated by Django 4.2.5 on 2023-10-17 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0005_alter_imagegallery_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='', max_length=100)),
                ('phone', models.TextField(default='', max_length=100)),
                ('address', models.TextField(default='', max_length=100)),
                ('value', models.TextField(default='', max_length=100)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id_orderdetail', models.BigAutoField(primary_key=True, serialize=False)),
                ('cart', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='application.cart')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='application.order')),
            ],
        ),
    ]
