# Generated by Django 4.2.5 on 2023-10-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='comment',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
